#!/bin/sh
# 
# Creates swap file in micro instances
# Copyright 2017 Bitnami.com All Rights Reserved
#

. /opt/bitnami/scripts/init/functions

SWAPFILE=/mnt/.bitnami.swap
SWAPSIZE=650000
instance_type=`get_generic_instance_type`
if [ "x$instance_type" = "xmicro" ] || [ "x$1" = "x--force" ] ; then
  if ! (swapon -s | grep -q $SWAPFILE) && test $SWAPSIZE -lt `df -k |grep -m1 -e '/$'|awk '{print $4}'`; then  
    rm -f $SWAPFILE
    dd if=/dev/zero of=$SWAPFILE bs=1K count=$SWAPSIZE
    chmod 0600 $SWAPFILE
    mkswap $SWAPFILE
    swapon $SWAPFILE
  fi
else
  rm -f $SWAPFILE
fi