#!/bin/sh
# 
# Get the default password that will be used for all services and applications
# Copyright 2017 Bitnami.com All Rights Reserved
#

. /opt/bitnami/scripts/init/functions

# when run with --force option, set the password regardless of flag
if [ "x$1" != "x--force" ] ; then
    run_once_globally_check "get_default_passwords"
    if [ $? -ne 0 ]; then
        exit 0
    fi
fi

# get if password should be modified
PASSWD="`get_applications_password`"

if [ "x$PASSWD" = "x" ] ; then
  exit 0
fi

# log at start as well since when changing takes long time to complete,
# get console output may not show the full log
echo ""
echo "#########################################################################"
echo "#                                                                       #"
echo "#        Setting Bitnami application password to '${PASSWD}'         #"
echo "#                                                                       #"
echo "#########################################################################"
echo ""