#!/bin/sh
#
# Change bitnamiftp user password
# Copyright 2017 Bitnami.com All Rights Reserved
#

. /opt/bitnami/scripts/init/functions

#Configure FTP
if [ "x$1" != "x" ] ; then
  echo "$1" >/root/bitnamiftp-pass
  # make sure ftp_password script is not run again
  run_once_globally_check "ftp_password"
else
  # only run once if password was not specified
  run_once_globally_check "ftp_password"
  if [ $? -ne 0 ]; then
    exit 0
  fi
  generate_random_password 50 > /root/bitnamiftp-pass
  if [ $? -ne 0 ]; then
    echo "Unable to generate random password - aborting"
    exit 1
  fi
fi

head -1 /root/bitnamiftp-pass >> /root/bitnamiftp-pass
head -2 /root/bitnamiftp-pass | passwd bitnamiftp

for BNCONFIG in /opt/bitnami/apps/*/bnconfig ; do
  $BNCONFIG --ftp_user bitnamiftp --ftp_password `head -1 /root/bitnamiftp-pass` 2>/dev/null 1>&2
done

rm -rf /root/bitnamiftp-pass